#!/bin/bash

export INBOX=${HOME}/.maildir
export FOLDER=${MBLAZE:-$HOME/.mblaze}/folder
export FOLDERS=${MBLAZE:-$HOME/.mblaze}/folders
export MAILCUR=${MBLAZE:-$HOME/.mblaze}/cur
export MAILSEQ=${MBLAZE:-$HOME/.mblaze}/seq

export MCOLOR_FROM=17
export MCOLOR_HEADER=17
export MCOLOR_QUOTE=52
export MCOLOR_QQUOTE=22
export MCOLOR_QQQUOTE=26
export MCOLOR_SEP=240
export MCOLOR_FOOTER=240
export MCOLOR_SIG=240

export IMAP_OPTS="plugin/lazy_expunge=expunged:lazy_expunge_only_last_instance=yes"

export MHBLAZE_BIN=${HOME}/mblaze-mh/bin
alias folder=${MHBLAZE_BIN}/folder.sh
alias folders=${MHBLAZE_BIN}/folders.sh
alias scan=${MHBLAZE_BIN}/scan.sh
alias show=${MHBLAZE_BIN}/show.sh
alias spam=${MHBLAZE_BIN}/spam.sh
alias expunge=${MHBLAZE_BIN}/expunge.py

alias in='scan .'

_folders() {
    COMPREPLY=( $(compgen -W "`cat ${FOLDERS}`" "${COMP_WORDS[COMP_CWORD]}" ) )
}

complete -F _folders folder scan

# build folder list
${MHBLAZE_BIN}/folders.sh -qr

